### ISSUE TITLE
bridge.call 方法传数据给js一直失败！

### ISSUE THREAD

**Issue by HZRZCW** [SDBridge/SDBridgeSwift#2]
webView.bridge.call(handlerName: jsMethodName, data: json) { responseData in
            Log(responseData, tag: "js返回的数据")

        }一直失败，js那边收不到数据导致界面白屏

**Comment by housenkui** [comment]
你那边看视频了吗？

Nanmenhaishao ***@***.***>于2022年6月22日 周三下午3:01写道：

**Comment by housenkui** [comment]
[](url
<img width="942" alt="iShot2022-06-22 15 03 55" src="https://user-images.githubusercontent.com/5885635/174965274-0c4ab39b-98d7-4019-a048-bb9972e06b74.png">
)

**Comment by HZRZCW** [comment]
> [](url <img alt="iShot2022-06-22 15 03 55" width="942" src="https://user-images.githubusercontent.com/5885635/174965274-0c4ab39b-98d7-4019-a048-bb9972e06b74.png"> )

看了视频还是一样，我用[WKWebViewJavascriptBridge](https://github.com/Lision/WKWebViewJavascriptBridge)这个框架大多数时候还是成功的，个别情况才失败，想换你这个试试，但是一直不成功。

**Comment by housenkui** [comment]
用法不对.```webView.bridge.call(handlerName: jsMethodName, data: json) { responseData in}```  要换

**Comment by housenkui** [comment]
```let data = ["iOSKey": "iOSValue"]
    bridge.call(handlerName: "GetToken", data: data) { responseData in
        guard let res = responseData else {
            print("Javascript console.log give native is nil!")
            return
        }
        print(res)
    }
```
```
bridge 对象不是挂在WkWebView上的.
```

**Comment by housenkui** [comment]
你如果先按照5视频，一步一步的完成. 怎么可能会用 ```webView.bridge.call ```

**Comment by HZRZCW** [comment]
> ```
>    bridge.call(handlerName: "GetToken", data: data) { responseData in
>        guard let res = responseData else {
>            print("Javascript console.log give native is nil!")
>            return
>        }
>        print(res)
>    }
> ```
> 
> ```
> bridge 对象不是挂在WkWebView上的.
> ```

我这个webView不是WKWebVIew，是一个View，持有wkwebview和bridge

**Comment by HZRZCW** [comment]
> > ```
> >    bridge.call(handlerName: "GetToken", data: data) { responseData in
> >        guard let res = responseData else {
> >            print("Javascript console.log give native is nil!")
> >            return
> >        }
> >        print(res)
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > bridge 对象不是挂在WkWebView上的.
> > ```
> 
> 我这个webView不是WKWebVIew，是一个View，持有wkwebview和bridge

<img width="653" alt="image" src="https://user-images.githubusercontent.com/12219811/174968501-eba5c922-bd80-4c3a-886d-e60f374d3624.png">

**Comment by housenkui** [comment]
我现在比较忙
，你那边有TeamViewer，可以远程吗？北京时间晚上10点以后.

**Comment by HZRZCW** [comment]
> 你先用我demo里面的html，加载看看能不能成功.

可以，我先试试demo，晚上再等你

**Comment by housenkui** [comment]
1.先保证，我的demo能成功；
2.再把demo里的html文件拖到，自己项目里看看能不能成功js和原生相互调用.

**Comment by HZRZCW** [comment]
> 1.先保证，我的demo能成功； 2.再把demo里的html文件拖到，自己项目里看看能不能成功js和原生相互调用.

Next line is Javascript console.log----->>>>>>>
WebViewJavascriptBridge: WARNING: no handler for message from ObjC:
Next line is Javascript console.log----->>>>>>>
{"callbackId":"objc_cb_1","handlerName":"JsHandler","data":"{"msg":"支付订单详情","content":"[{\"number\":\"10\",\"bestPrice\":200,\"goodsAmount\":\"2000\",\"goodsInfo\":{\"name4\":\"\",\"coverImage\":\"https:\\\/\\\/cdn.redden-tech.com\\\/server\\\/server-shop\\\/20220528\\\/f9dcc9d94e8443529febdf6f8f6c6f35.png\",\"deliveryTypeList\":[1],\"price\":200,\"goodsId\":1529447207076433920,\"desc4\":\"\",\"desc5\":\"\",\"name2\":\"Kweichow Moutai Group Co., Ltd. Moutai Bu Lao wine 53 degrees sauce-flavor liquor Tasting Suite\",\"desc3\":\"\",\"name3\":\"\",\"brandId\":1529033342916300800,\"categoryId\":10000,\"desc2\":\"Kweichow Moutai Group Co., Ltd. Moutai Bu Lao wine 53 degrees sauce-flavor liquor Tasting Suite\",\"name1\":\"贵州茅台集团公司出品 茅台不老酒 53度酱香型白酒 杯装\",\"unit\":3,\"specs\":\"5ml\",\"desc1\":\"贵州茅台集团公司出品 茅台不老酒 53度酱香型白酒 杯装\",\"name5\":\"\"}}]","code":8}"}
Next line is Javascript console.log----->>>>>>>
end hook Console.
Next line is Javascript console.log----->>>>>>>
hook Console have already finished.

打印这些日志

**Comment by housenkui** [comment]
可以再等 20分钟吗？ 先加我QQ:840737320

**Comment by HZRZCW** [comment]
> 840737320

OK
