### ISSUE TITLE
iOS 12.1崩溃

### ISSUE THREAD

**Issue by wuxiaohaoios** [SDBridge/SDBridgeSwift#3]
删除hookConsole的代码12.1会崩溃 ，不删除的话自动播放音频失败。

**Comment by housenkui** [comment]
js那边console.log，代码是什么样的方便发一下吗？

**Comment by housenkui** [comment]
能发一下奔溃的函数调用栈吗？

**Comment by housenkui** [comment]
pod 'SDBridgeSwift', '~> 1.1.0' ，bug 已经修复.
